---
- name: Spawn EC2 Instance
  ec2:
    ec2_url: "{{ec2_url}}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_type: "{{ instance_type }}"
    assign_public_ip: "{{public_ip}}"
    image: "{{ image }}"
    instance_tags:
      Name: "{{ tag_image }}"
    group: "{{group}}"
  register: output
  
